name: Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-attw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24.18.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Check if types are wrong with attw
        run: npx -p @arethetypeswrong/cli attw --pack --profile esm-only .

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24.18.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run checks
        run: npm run check
      - name: Run tests with coverage
        run: npm test
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/

  ci-gate:
    needs:
      - check-attw
      - test-coverage
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed or skipped
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
